export const bookSeed = [
  {
    title: 'El Resplandor',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 1,
    genreId: 1,
    price: 25000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Misery',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 1,
    genreId: 1,
    price: 18000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Némesis',
    description: 'Lorem Ipsum',
    authorId: 3,
    editorialId: 2,
    genreId: 3,
    price: 30000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Ecce Homo',
    description: 'Lorem Ipsum',
    authorId: 5,
    editorialId: 3,
    genreId: 4,
    price: 30000,
    isAvailable: true,
    isActive: true,
  },
];
