export const bookSeed = [
  {
    title: 'El Resplandor',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 1,
    genreId: 3,
    price: 25000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Misery',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 1,
    genreId: 3,
    price: 18000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'Némesis',
    description: 'Lorem Ipsum',
    authorId: 3,
    editorialId: 2,
    genreId: 3,
    price: 30000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Ecce Homo',
    description: 'Lorem Ipsum',
    authorId: 5,
    editorialId: 3,
    genreId: 4,
    price: 30000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'Fundación',
    description: 'Lorem Ipsum',
    authorId: 2,
    editorialId: 1,
    genreId: 1,
    price: 22000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Yo, Robot',
    description: 'Lorem Ipsum',
    authorId: 2,
    editorialId: 2,
    genreId: 1,
    price: 21000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'Asesinato en el Orient Express',
    description: 'Lorem Ipsum',
    authorId: 3,
    editorialId: 1,
    genreId: 3,
    price: 19000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'El asesinato de Roger Ackroyd',
    description: 'Lorem Ipsum',
    authorId: 3,
    editorialId: 3,
    genreId: 3,
    price: 20000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'Más allá del principio del placer',
    description: 'Lorem Ipsum',
    authorId: 4,
    editorialId: 4,
    genreId: 5,
    price: 24000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'La interpretación de los sueños',
    description: 'Lorem Ipsum',
    authorId: 4,
    editorialId: 2,
    genreId: 5,
    price: 26000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'Así habló Zaratustra',
    description: 'Lorem Ipsum',
    authorId: 5,
    editorialId: 1,
    genreId: 4,
    price: 23000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Más allá del bien y del mal',
    description: 'Lorem Ipsum',
    authorId: 5,
    editorialId: 4,
    genreId: 4,
    price: 27000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'It',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 2,
    genreId: 3,
    price: 28000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Carrie',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 3,
    genreId: 3,
    price: 19000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'Cuentos completos',
    description: 'Lorem Ipsum',
    authorId: 2,
    editorialId: 4,
    genreId: 1,
    price: 30000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Los crímenes del monograma',
    description: 'Lorem Ipsum',
    authorId: 3,
    editorialId: 3,
    genreId: 3,
    price: 21000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'El yo y el ello',
    description: 'Lorem Ipsum',
    authorId: 4,
    editorialId: 1,
    genreId: 5,
    price: 22000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'La genealogía de la moral',
    description: 'Lorem Ipsum',
    authorId: 5,
    editorialId: 2,
    genreId: 4,
    price: 25000,
    isAvailable: false,
    isActive: true,
  },
  {
    title: 'La torre oscura',
    description: 'Lorem Ipsum',
    authorId: 1,
    editorialId: 4,
    genreId: 3,
    price: 26000,
    isAvailable: true,
    isActive: true,
  },
  {
    title: 'Ensayo sobre el entendimiento humano',
    description: 'Lorem Ipsum',
    authorId: 4,
    editorialId: 2,
    genreId: 5,
    price: 24000,
    isAvailable: false,
    isActive: true,
  },
];
